### ISSUE TITLE
Update installers for Inkscape 0.91

### ISSUE THREAD

**Issue by oskay** [evil-mad/wcb-ink#38]
Inkscape 0.91 will be released soon ("weeks to months"), and we would like to be ready. The current installer is not compatible with Inkscape 0.91.

Todo:

Check compatibility of Inkscape extensions with 0.91
Update installers with new file locations for 0.91.

For MacOS, the location of extensions in Inkscape 0.48.5 is:
/Applications/Inkscape.app/Contents/Resources/extensions/

However, in 0.91 the new location is:
/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions

See also https://github.com/evil-mad/EggBot/issues/19

**Comment by Dewb** [comment]
In case anyone else is looking to use 0.91, I can report that changing the Contents/Resources paths to Contents/Resources/share/inkscape in the following three files allowed me to install and use the extension with Inkscape 0.91.
 
Contents/distribution.dist
Contents/Packages/extensions.pkg/Contents/Info.plist
Contents/Packages/templates.pkg/Contents/Info.plist

**Comment by oskay** [comment]
Ideally, we'll add a version check to do this automatically. :P

**Comment by oskay** [comment]
Closing with release of software version 1.1 today.
