### ISSUE TITLE
Trouble connecting to EBB in MacOS X El Capitan

### ISSUE THREAD

**Issue by oskay** [evil-mad/wcb-ink#42]
USB serial port appears to work normally _once_ after disconnecting and reconnecting USB cable. 

Perhaps the port is not being closed correctly within pyserial?

**Comment by oskay** [comment]
I've made some progress, by running independent python test scripts. Presented in glorious pseudocode.

    //Define Test Procedure A
     Open serial port TheSerialPort
     Query (version number)
     versionNumber = Read serial input
     Print versionNumber
     Close TheSerialPort

Plug in USB cable. 
Run _Test Procedure A_.
Result:  `EBBv13_and_above EB Firmware Version 2.0.1`

Run _Test Procedure A_, again.
Result:  [no output] 

Run _Test Procedure A_, again.
Result:  [no output] 


The _apparent_ case is that the USB port becomes inaccessible after being used just once.  Try another test, though, where we query the EBB more than once:

    //Define Test Procedure B
     Open serial port TheSerialPort
     Query (version number)
     versionNumber = Read serial input
     Print versionNumber
     Query (version number)
     versionNumber = Read serial input
     Print versionNumber
     Close TheSerialPort

Plug in USB cable. 
Run _Test Procedure B_.
Result:  `EBBv13_and_above EB Firmware Version 2.0.1`
Result:  `EBBv13_and_above EB Firmware Version 2.0.1`

Run _Test Procedure B_, again.
Result:  [no output] 
Result:  `EBBv13_and_above EB Firmware Version 2.0.1`

Run _Test Procedure B_, again.
Result:  [no output] 
Result:  `EBBv13_and_above EB Firmware Version 2.0.1`


So... it appears that it *may* be _only the first_ attempt to connect in each subsequent session that is not working. If we add additional queries (and actions) within the same session, they do appear to work correctly.

**Comment by oskay** [comment]
Apparently functional workaround!  

Within the function `testSerialPort`,

replace 

    strVersion = serialPort.readline()

with

    strVersion = serialPort.readline()
    if strVersion and strVersion.startswith( 'EBB' ):
        return serialPort
    serialPort.write( 'v\r' )  #Try a second query for El Capitan
    strVersion = serialPort.readline()		


[elcap_patch.txt](https://github.com/evil-mad/wcb-ink/files/8982/elcap_patch.txt)

**Comment by asadowsky** [comment]
Bummer. The El Cap upgrade killed mine too. Not sure how to implement this patch.

**Comment by oskay** [comment]
Please try this procedure.

Download this file:
https://raw.githubusercontent.com/evil-mad/wcb-ink/master/extensions/wcb.py

Save that file as plain text, with file name "wcb.py".  Move that file into this folder: /Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/

You can get there by selecting from the menu bar in the finder: Go > Go to Folder... , and pasting that directory name there.

**Comment by asadowsky** [comment]
Ah, I should have mentioned that the device I'm having trouble with is the Eggbot (pro).

**Comment by oskay** [comment]
Perhaps you meant to comment here, then? 
https://github.com/evil-mad/EggBot/issues/31

**Comment by oskay** [comment]
New release for Mac, with update for El Capitan:
https://github.com/evil-mad/wcb-ink/releases/tag/1.2.1
